### ISSUE TITLE
Adding tracking of rename events

### ISSUE THREAD

**Issue by vguillet** [LordGrimmauld/aw-watcher-obsidian#1]
First of all, thank you so much for this! This is THE plugin I had been waiting for. The logs are amazing. They however seem to miss one key event, making it impossible to fully reconstruct the activity timeline properly. If it was possible to also **log note rename events** (with the original name and the new one at once), it would then be possible to properly trace back the time spend on a specific note/set on the information. Cheers in advance!

Note: This could even be a duration=0 event, as long as it is logged to allow for continuity!

**Comment by LordGrimmauld** [comment]
That is a good idea!
I'll need to do some more reading up on Obsidians plugin API to actually hook Obsidian events in the first place instead of just looking at the open Leaf on a clock, but i'll certainly look into it.

**Comment by vguillet** [comment]
That would indeed probably also improve performance and log quality! Plus that could also allow for logging note creation. (Could be nice for also getting better insight on note production rate and patterns)

**Comment by LordGrimmauld** [comment]
Alright. I added preliminary zero-duration event tracking. The relevant files for testing can be found in the [GitHub actions](https://github.com/LordGrimmauld/aw-watcher-obsidian/actions/runs/3984737734).
I am not completely certain about whether this is the proper way to do it, but it seems to at least show the events in "Raw Data" view of ActivityWatch.
Tested on Obsidian 1.1.9 and ActivityWatch dev server linux AUR 0.12.1.

Do let me know whether this fulfills your usecase.

**Comment by vguillet** [comment]
That was quick XD. Ill see if I can give it a try, ill let you know asap. Just having the events in the raw logs should be plenty to do some pretty dope data mining/machine learning!

**Comment by vguillet** [comment]
Can't seem to import the plugin (tried BRAT on the correct branch, which gives me a manifest.json file missing error). Any pointers on how to install it?

**Comment by vguillet** [comment]
Though looking at the code there seems to be functions for tracking file create/rename/delete, which is exactly what I was looking for!

**Comment by LordGrimmauld** [comment]
Ah i believe i'd need to make an actual release for BRAT to work (i never worked with BRAT, but looking at how obsidian plugins handle things i think that might fix things).
It might work now that i put up a [pre-release](https://github.com/LordGrimmauld/aw-watcher-obsidian/releases/tag/1.2.0)?
There is always the manual way by downloading and placing the files from the previously linked github actions, but i realize that solution is not optimal.

**Comment by vguillet** [comment]
Yep, got it to work with your instructions, and it works wonders!

![image](https://user-images.githubusercontent.com/43042800/214011505-2177384d-11f6-4254-ad54-0b65bbecb71f.png)

It might be nice to clean up the eventType to be just createFileEvent/deleteFileEven/renameFileEvent/activeFileEvent, but that's pretty minor.

Thanks again for the awesome work! Can't understate how valuable I think this is going to be in the long term!

**Comment by LordGrimmauld** [comment]
I'll think about simplifying the eventType, this was what i came up with when looking at how the JetBrains watcher handles different types of events and is not set in stone. You can have your evaluator split on dot and take the last one, that should future-proof your evaluation, whether i simplify the eventType or not.

**Comment by vguillet** [comment]
Indeed, its not hard at all to clean up on my side if need be. Cheers for being so reactive!

**Comment by LordGrimmauld** [comment]
Alright, ended up renaming to `obsidian.renameFileEvent` and similar. I also made a non-beta release 1.2.1 to ease testing for people using the github release channel (e.g. through obsidians BRAT).
I'll be closing this issue for now, but i'll be sure to keep track of what other event types Obsidian allows subscribing to in their API and might log those too in the future.
